[project]
uuid = "realism-serverless"
name = "Realism Image Processing"

[build]
base_image = "runpod/pytorch:2.1.0-py3.10-cuda11.8.0-devel-ubuntu22.04"
python_version = "3.10"
cuda_version = "11.8"
# Cache bust to force fresh build - 2025-06-14-21:35
build_id = "v2025-06-14-21-35"
# Force cache bust - 2025-06-14-21:30
cache_bust = "2025-06-14-21:30"

[build.env_vars]
PYTHONPATH = "/runpod-volume/ComfyUI"
PYTHONUNBUFFERED = "1"
PYTHONVERBOSE = "1"
PYTHONDEBUG = "1"
PYTHONWARNINGS = "default"
RUNPOD_DEBUG = "1"
RUNPOD_LOG_LEVEL = "DEBUG"
RUNPOD_WORKER_LOG_LEVEL = "DEBUG"
RUNPOD_VERBOSE = "1"
DEBUG = "1"
VERBOSE = "1"

[runtime]
handler = "handler.handler"
python_version = "3.10"
gpu_types = []
min_upload_speed = 1000
min_download_speed = 1000
container_disk_in_gb = 20
memory_in_gb = 16
cpu_count = 4

[runtime.env_vars]
PYTHONPATH = "/runpod-volume/ComfyUI"
PYTHONUNBUFFERED = "1"
PYTHONVERBOSE = "1"
PYTHONDEBUG = "1"
PYTHONWARNINGS = "default"
RUNPOD_DEBUG = "1"
RUNPOD_LOG_LEVEL = "DEBUG"
RUNPOD_WORKER_LOG_LEVEL = "DEBUG"
RUNPOD_VERBOSE = "1"
DEBUG = "1"
VERBOSE = "1"
CUDA_LAUNCH_BLOCKING = "1"
TORCH_SHOW_CPP_STACKTRACES = "1"

[runtime.network_volume]
name = "Netwrok Storage"
mount_path = "/runpod-volume"
