[project]
uuid = "realism-serverless"
name = "Realism Image Processing"

[build]
base_image = "runpod/pytorch:2.1.0-py3.10-cuda11.8.0-devel-ubuntu22.04"
python_version = "3.10"
cuda_version = "11.8"

[build.env_vars]
PYTHONPATH = "/runpod-volume/ComfyUI"
PYTHONUNBUFFERED = "1"

[runtime]
handler = "handler.handler"
python_version = "3.10"
gpu_types = []
min_upload_speed = 1000
min_download_speed = 1000

[runtime.env_vars]
PYTHONPATH = "/runpod-volume/ComfyUI"
PYTHONUNBUFFERED = "1"

[runtime.network_volume]
name = "Netwrok Storage"
mount_path = "/runpod-volume"
